### ISSUE TITLE
Repo/Tracker Improvements [Mega Issue]

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#431]
This rolls in #423, #378, #159 into a single issue, and allows for discussion and the addition of potential improvements to the following checklist, via edits I will make whenever a new improvement is approved:

- [ ] (https://github.com/absoIute/Mega-Hack-Pro-Future/issues/423#issue-1117713735) Compiled list _(See: https://github.com/absoIute/Mega-Hack-Pro-Future/issues/423#issuecomment-1024976278, https://github.com/absoIute/Mega-Hack-Pro-Future/issues/423#issuecomment-1025015045)_ of all added features that were suggested by users on the tracker in the README.md so new users will see how the community is helping MH grow.
- [ ] (https://github.com/absoIute/Mega-Hack-Pro-Future/issues/423#issue-1117713735) Changelog listing additions/fixes for each new version.
- [ ] (https://github.com/absoIute/Mega-Hack-Pro-Future/issues/423#issue-1117713735) Utilising the "Releases" section on GitHub to notify users of each new released update.
- [ ] (DM Discussion) Migration of the issue tracker from Github to a self-hosted environment.
- [ ] (https://github.com/absoIute/Mega-Hack-Pro-Future/issues/159#issue-1041800178) Migrate pinned issues to a FAQ/Documentation page if appropriate.

**Comment by Brittank88** [comment]
> [ ] ([(Meta) Issue Tracker Suggestions #423 (comment)](https://github.com/absoIute/Mega-Hack-Pro-Future/issues/423#issue-1117713735)) Compiled list _(See: [(Meta) Issue Tracker Suggestions #423 (comment)](https://github.com/absoIute/Mega-Hack-Pro-Future/issues/423#issuecomment-1024976278), [(Meta) Issue Tracker Suggestions #423 (comment)](https://github.com/absoIute/Mega-Hack-Pro-Future/issues/423#issuecomment-1025015045))_ of all added features that were suggested by users on the tracker in the README.md so new users will see how the community is helping MH grow.

Thinking it would be good for each entry to link to the logged issue that resulted in its implementation. Thoughts?

**Comment by Nicko2102** [comment]
from #389 
i think this (added label) could also be implemented as part of #423, as a way to track those sort of things on github. Also, to make it cleaner, there could be an "added" label alongside a "ready label", or something like that, although that seems like it might be a bit too much work...

**Comment by MainConMan** [comment]
> > [ ] ([(Meta) Issue Tracker Suggestions #423 (comment)](https://github.com/absoIute/Mega-Hack-Pro-Future/issues/423#issue-1117713735)) Compiled list _(See: [(Meta) Issue Tracker Suggestions #423 (comment)](https://github.com/absoIute/Mega-Hack-Pro-Future/issues/423#issuecomment-1024976278), [(Meta) Issue Tracker Suggestions #423 (comment)](https://github.com/absoIute/Mega-Hack-Pro-Future/issues/423#issuecomment-1025015045))_ of all added features that were suggested by users on the tracker in the README.md so new users will see how the community is helping MH grow.
> 
> Thinking it would be good for each entry to link to the logged issue that resulted in its implementation. Thoughts?

I like this idea! I don't see any reason not to do this.

**Comment by Brittank88** [comment]
> from #389 i think this (added label) could also be implemented as part of #423, as a way to track those sort of things on github. Also, to make it cleaner, there could be an "added" label alongside a "ready label", or something like that, although that seems like it might be a bit too much work...

I also like this. Yes, it will take effort to go find every implemented issue and apply the "Added" label to it, but it would be worth it, and it could disambiguate between something being "approved" and actually making its way into a release (because it seems that those on a Venn diagram are indeed not a circle...).

@MainConMan You made that original list of features that have since been implemented - is that everyone? I'd be surprised if it was considering we've passed the 400 issue mark, but if so then fair enough. I'd just like to not be on my own in finding every issue that would need this label applied to it.

**Comment by MainConMan** [comment]
> @MainConMan You made that original list of features that have since been implemented - is that everyone? I'd be surprised if it was considering we've passed the 400 issue mark, but if so then fair enough. I'd just like to not be on my own in finding every issue that would need this label applied to it.

The list didnt include bugs, only enhancements, but it was every added enhancement I could find. Would it be helpful if I were to make a list with links? And if so, would you want me to include bugs (or any other label)?

**Comment by Brittank88** [comment]
> Would it be helpful if I were to make a list with links?

This would be so wonderful!

> And if so, would you want me to include bugs (or any other label)?

As a separate list, that would be very cool!

Please don't feel obligated to do it though, you've been super helpful already and I can't thank you and others (Zohnannor, Nicko2102, etc. looking at you guys ❤️) enough.

> I forgot to mention this, and I probably should, but the first 3 issues by Absolute I did not include.

Yeah, if this list is for crediting and showing off the contributions of those in the community, including Absolute's own issues doesn't make much sense.

**Comment by MainConMan** [comment]
Alright, I'll make a separate list, and include all issues regardless of labels. I'll start when I get home, and update this message with my progress! :)

**Comment by MainConMan** [comment]
I finished the lists! There seems to be a lot more enhancements then on the last list, I guess it's because of how I sorted the issues to make the last list. I'm very sorry about that. This time, I went through EVERY issue, so that won't be a problem this time!

[MHv7 Issue Tracker Thing.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7975132/MHv7.Issue.Tracker.Thing.txt)

Enhancements
Brittank88 - Z-Layer 0 Bypass - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/6
Brittank88 - Mouse Becomes Visible When Overlay is Open - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/9
Brittank88 - Rotation Modifier - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/10
WEGfan - Practice Pickup Coins - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/12
Brittank - No Respawn Flash - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/19
Conlinkin - Coins Show Uncollected - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/20
Brittank88 - Startpos Lag Fix - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/22
Fl1pNatic & Brittank88 - Cheat Indicator - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/24
Zohnannor - Tooltips - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/29
Brittank88 - Unfocused FPS - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/30
Brittank88 - Behaviour of "NoClip Accuracy" - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/33
Brittank88 - Dynamic Menu Length - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/34
jojo989 - Classic Speed Hack - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/37
Wukarditd - Disable Hide Trigger - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/55
gggeo0513 - Auto Pickup Coins - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/63
Aktimoose - Icon Level Colours - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/73
Brittank88 - Granular Extension / Absolutedlls Load Order - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/81
Fl1pNatic - Noclip Deaths - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/83
Fl1pNatic - Experimental Noclip Accuracy - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/84
Brittank88 - Hide UI Doesn't Hide Link Buttons - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/87
Brittank88 - Hide UI // BetterEdit Compatibility - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/90
pHellowWorld - Void Click Bug Fix - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/96
AdyaGD - Change Colours of 2nd Dual Icon - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/105
RealBikas - 0% Practice Complete - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/106
patrykchrymecki - Better Safe Mode - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/121
Fl1pNatic - Noclip Accuracy Damage Tint Colour - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/127
patrykchrymecki - Hitbox Colour Customization - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/128
alexmalex2007 - Low Detail Option - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/131
LinkeddGD - Color 1 / Color 2 Pulse w/ BG / Pastel - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/133
Md915 - Hide Pause Layer - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/140
Yuukinoo - Mute on Unfocus - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/143
BlockOG - Show Layout - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/148
Brittank88 - Pause During Complete - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/152
Brittank88 - Input Box Copy/Paste Support - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/153
Joel055 - "Uncomplete Level" Reset Orbs/Coins - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/163 (resets orbs, but not coins)
Fl1pNatic - Blending Modes For Colour Options (+ P1 / P2 Swap) - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/167
NewAlexGamer - Favourites Tab - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/168
Fl1pNatic - Make pressing space on level complete screen start the level over - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/208
GDSaneS - Legit Indicator - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/210
fedqq - Better Startpos Switcher - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/272 (3 and 4 added, 1 and 2 not added)
Fl1pNatic - Make "Session Time" Status Run in Real Time - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/273
MainConMan - Last Death Status - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/274 (added in beta 5, but replaced for "best run" in beta 6)
MainConMan - Stop Move Triggers on Death - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/286
BrownieGamingX5 - Set Labels/Status Opacity - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/304


Bugs
Brittank88 - "Hide UI" Option Requires Editor Pause Toggle - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/4
Brittank88 - Set Scale Doesn't Support Negatives - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/17
Brittank88 - Borderless Fullscreen Fails - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/31
CoolDawg08 - Random Game Freezing - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/44
NEM3S - Solid Colour Failure - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/53
dyfw - Instant Complete Crash w/ 2-Player Start - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/56
Fliare - Death Effect Always Disabled - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/61
OctahedronV2 - No-Clip Accuracy Doesn't Activate Cheat Indicator - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/65
dankmeme01 - Created Levels Verified w/ < 100% Noclip Accuracy - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/71
Aktimoose - Auto Music Sync + Practice Music Hack - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/101
VIKI155 - CPS Counter Doesn't Work With Bots - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/108
patrykchrymecki - CPS Counter Showing In Keybinds - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/122
Brittank88 - Full-Height Menu Bug - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/158
patrykchrymecki - Show Hitboxes Crash - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/175
NewAlexGamer - Multiple hacks/mods cannot be set on the same key - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/177
NewAlexGamer - "Set Scale" Doesn't Save - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/179
NewAlexGamer - "Auto Music Sync" Game Freeze on Level Exit - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/181
KitKat63916 - Run extension overlaps - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/188
sinc0s - Using start-pos switcher in normal mode crashes game - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/190
KitKat63916 - Typing Messages Triggers Keybinds - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/192
nicko2102 - Noclip Accuracy Overridden By 0% Practice - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/198
noeruchangd - Lock Cursor Not Working - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/200
noeruchangd - Toggle for Free Window Resize and/or Save Resolution Settings - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/202
noeruchangd - Level Complete Screen & Start Pos Switcher - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/203
patrykchrymecki - Toggling % in pause menu sets in game clock to 00:00:00 - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/204
patrykchrymecki - Tint On Death Enables Experimental - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/205
mrhotmadm - Rainbow Icon fails on Robot and Spider - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/211
Fl1pNatic - Game is Extremely Nnstable - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/216
dankmeme01 - Wrong tooltip for "Auto Song Download" - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/217
kenar-f - CPS/FPS Display Broken - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/218
CreeperSword - Phantom Wave Trail - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/224
CyberCat30 - Music Flash green and blue channels swap - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/225
dankmeme01 - Slope Physics Bug w/ Noclip - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/228
ImmensityHQ - Respawn at Last Checkpoint Doesn't Hide Mouse - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/230
zohnannor - "Player Trail" Does Nothing - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/245
zohnannor - "Fill Hitbox" Multiple Application Bug - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/246
Sloweneuh - Dash Orb Fire, Robot Glow, Spider Glow Are Secondary Color/Glow Even If Those Are RGB - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/247
NewAlexGamer - "Disable In Editor" Works After Clicking Save and Play - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/248
NewAlexGamer - Speedhack Value Resetting - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/250
totallyphysicallypossible - Noclip Enables Itself After Restart - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/255
NewAlexGAmer - "Disable In Editor" Not Working - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/282
Aktimoos - Icon Effects Don't Work on Spider or Robot Glows - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/289 (Dupe of 247?)
BrownieGamingX5 - Speedhack Resets Back To 1x - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/291 (dupe of 250?)
totallyphysicallypossible - Can't Paste In MH Text Inputs - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/293 (Dupe of 153?)
totallyphysicallypossible - Best Run Updates When Using Noclip - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/295
SadShikawa - Icon Hack Doesn't Save Icons - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/296 (Fixed before issue was created)
BrownieGamingX5 - Start Pos At The Endscreen Is 1% Off - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/297
Fl1pNatic - "Icons" Module Doesn't Work - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/311 (Dupe of 296?)
TheTruePringle - Random Icons Seems Predetermined - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/318
NewAlexGamer - "Best Run" Text Doesn't Show Runs to 100% - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/319
BrownieGamingX5 - X/Y/Z Variable Object Edit Delete - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/320
BrownieGamingX5 - Speedhack Game Crash Reset - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/352
NewAlexGamer - Best Run Sometimes Shows >100% - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/364
Nicko2102 - Erebus Positioning? - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/375


Other
Brittank88 - absolllute.com/contact References The Tracker - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/35
patrykchrymecki - Transition Customizer - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/103 (Brought back from mhv5)
benjaYTn - Gifting System - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/157
zohnannor - RGB Icons Speed - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/180 (Brought back from mhv6)
feytox - Thread Priority - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/215 (Brought back from mhv6)
patrykchrymecki - Website Still Says "Mega Hack v6 Pro" - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/223
patrykchrymecki - Website Displays Wrong Title - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/265
patrykchrymecki - Website Shows Wrong Text - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/275

Notes: I did not include the first 3 issues by Absolute. Some issues have notes after them in parentheses. I didn't Include Issue #18, If you want me to add it, I can update my message. :)

**Comment by Brittank88** [comment]
> This time, I went through EVERY issue

Are you sure you didn't descend down from the heavens you are a god wtf thank you

**Comment by Brittank88** [comment]
@absoIute Idea I just had - if we actually make use of the milestones feature we can much more easily track which issues went into which update. We just make a new milestone for each new update version, and add issues to it as they become upcoming. This actually removes the need for the upcoming label, as we inherently know they're upcoming by the fact that they are present in the milestone.

Would love to know what everyone else thinks of this too!

**Comment by MainConMan** [comment]
> Are you sure you didn't descend down from the heavens you are a god wtf thank you

Happy to help! :)

**Comment by Brittank88** [comment]
> (Dupe of 153?)

Technically not - one was implementing for the extensions API, whilst the other was a bug in the default input boxes. I'd consider them separate.

> (Dupe of 247?)
> (dupe of 250?)
> (Dupe of 296?)

I think you're correct on these. Have marked them as duplicates just to be thorough.

Let me know if I missed any other dupes you noted!

**Comment by MainConMan** [comment]
> > (Dupe of 153?)
> 
> Technically not - one was implementing for the extensions API, whilst the other was a bug in the default input boxes. I'd consider them separate.
> 
> > (Dupe of 247?)
> > (dupe of 250?)
> > (Dupe of 296?)
> 
> I think you're correct on these. Have marked them as duplicates just to be thorough.
> 
> Let me know if I missed any other dupes you noted!

I think that's all of them. Should I edit my message to remove the 3 that were? Or should I just leave them in?

**Comment by Brittank88** [comment]
> 

Leave them in - btw I'm gonna edit your message very soon with it all formatted into a nice markdown table!

[Awarest-Align](https://marketplace.visualstudio.com/items?itemName=awarest.awarest-align) is such a cool VSCode extension, it made this process so much quicker.

**Comment by MainConMan** [comment]
> btw I'm gonna edit your message very soon with it all formatted into a nice markdown table!

Good idea! Thanks :)

**Comment by Nicko2102** [comment]
> @absoIute Idea I just had - if we actually make use of the milestones feature we can much more easily track which issues went into which update. We just make a new milestone for each new update version, and add issues to it as they become upcoming. This actually removes the need for the upcoming label, as we inherently know they're upcoming by the fact that they are present in the milestone.
> 
> Would love to know what everyone else thinks of this too!

Love this idea, honestly if it makes things easier for everyone then i'm all for it

**Comment by Nicko2102** [comment]
> [MHv7 Issue Tracker Thing.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7975132/MHv7.Issue.Tracker.Thing.txt)

could have sworn i had more than 2 things 🤔

**Comment by MainConMan** [comment]
> > [MHv7 Issue Tracker Thing.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7975132/MHv7.Issue.Tracker.Thing.txt)
> 
> could have sworn i had more than 2 things 🤔

It only includes things that are already implemented (as of v7 gm1), that's probably why.

**Comment by MainConMan** [comment]
The table looks so much better than what I had originally. Good job Brittank!

**Comment by Brittank88** [comment]
> > > [MHv7 Issue Tracker Thing.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7975132/MHv7.Issue.Tracker.Thing.txt)
> > 
> > 
> > could have sworn i had more than 2 things 🤔
> 
> It only includes things that are already implemented (as of v7 gm1), that's probably why.

Probably for the best - trying to dig all the way back to MHv6 would be a big project in itself.

**Comment by Brittank88** [comment]
> The table looks so much better than what I had originally. Good job Brittank!

I know when you go to edit it, it looks kinda broken, but that's just because the lines are too long. Wish this thread took advantage of how wide PC screens usually are. Maybe I can author a Tampermonkey extension to fix that.

**Comment by Nicko2102** [comment]
> > > [MHv7 Issue Tracker Thing.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7975132/MHv7.Issue.Tracker.Thing.txt)
> > 
> > 
> > could have sworn i had more than 2 things 🤔
> 
> It only includes things that are already implemented (as of v7 gm1), that's probably why.

oh right lol

**Comment by MainConMan** [comment]
> > > > [MHv7 Issue Tracker Thing.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7975132/MHv7.Issue.Tracker.Thing.txt)
> > > 
> > > 
> > > could have sworn i had more than 2 things 🤔
> > 
> > 
> > It only includes things that are already implemented (as of v7 gm1), that's probably why.
> 
> Probably for the best - trying to dig all the way back to MHv6 would be a big project in itself.

I may be misinterpreting, but it does include things added from all updates. I meant that the list doesn't include any issues if they haven't been added.

**Comment by Nicko2102** [comment]
> > > > > [MHv7 Issue Tracker Thing.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7975132/MHv7.Issue.Tracker.Thing.txt)
> > > > 
> > > > 
> > > > could have sworn i had more than 2 things 🤔
> > > 
> > > 
> > > It only includes things that are already implemented (as of v7 gm1), that's probably why.
> > 
> > 
> > Probably for the best - trying to dig all the way back to MHv6 would be a big project in itself.
> 
> I may be misinterpreting, but it does include things added from all updates. I meant that the list doesn't include any issues if they haven't been added.

I think Brittank might have understood actually, i think you were clarifying that you aren't including any "upcoming" hacks

**Comment by Brittank88** [comment]
> Maybe I can author a Tampermonkey extension to fix that.

Just wrote this line which you can add to your blocklist in uBlock Origin to fix this!
`github.com##div.container-xl:style(max-width: calc(100vw - 128px) !important)`

You can adjust the `128px` to increase/decrease the overall width of everything.

**Comment by MainConMan** [comment]
> > The table looks so much better than what I had originally. Good job Brittank!
> 
> I know when you go to edit it, it looks kinda broken, but that's just because the lines are too long. Wish this thread took advantage of how wide PC screens usually are. Maybe I can author a Tampermonkey extension to fix that.

Lmao, yeah. It shouldn't be too hard to work around if one of us ever needs to. NVM as I was typing this you found a fix!

**Comment by Brittank88** [comment]
> NVM as I was typing this you found a fix!

Fix part two: Forcing a monospaced font within the comment edit textarea with the following line:

`github.com##textarea.comment-form-textarea:style(font-family: 'Courier New', monospace !important)`

**Comment by Brittank88** [comment]
![image](https://user-images.githubusercontent.com/24266948/151902679-ad235082-b6d4-4d2b-bae3-cadb3859237c.png)

SO MUCH BETTER

**Comment by Brittank88** [comment]
(Seriously I recommend uBlock Origin regardless it's really good at blocking certain things that are typically hard to block - for example, it can actually remove classes from HTML elements which bypasses some no-scroll stuff on websites).

**Comment by MainConMan** [comment]
> (Seriously I recommend uBlock Origin regardless it's really good at blocking certain things that are typically hard to block - for example, it can actually remove classes from HTML elements which bypasses some no-scroll stuff on websites).

Already have it installed! Thanks! :D

**Comment by MainConMan** [comment]
> [MHv7 Issue Tracker Thing.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7975132/MHv7.Issue.Tracker.Thing.txt)

I was reading over this 1 more time, and found a mistake I made. #364 should have upcoming, and should be removed from the table. Very sorry about that. 

I will update the table to remove it when I get home,  unless Brittank or Absolute do it before then.

**Comment by Nicko2102** [comment]
also for # 198 can you capitalize my name? ik its a small thing but its capital in the other row so it looks a little off thanks :D

**Comment by MainConMan** [comment]
> also for # 198 can you capitalize my name? ik its a small thing but its capital in the other row so it looks a little off thanks :D

Yes I will, and I'll also fix any other spelling/capitalization error I find!

**Comment by absoIute** [comment]
> @absoIute Idea I just had - if we actually make use of the milestones feature we can much more easily track which issues went into which update. We just make a new milestone for each new update version, and add issues to it as they become upcoming. This actually removes the need for the upcoming label, as we inherently know they're upcoming by the fact that they are present in the milestone.
> 
> Would love to know what everyone else thinks of this too!

will start to do this ngl sounds good, will go through previous updates too

**Comment by absoIute** [comment]
> Also, I found this, it could be a good way to automatically list people whose input has resulted in implemented features: https://allcontributors.org/

added the bot! that's one hell of a list

**Comment by Brittank88** [comment]
> also for # 198 can you capitalize my name? ik its a small thing but its capital in the other row so it looks a little off thanks :D also can i nominate MainConMan for repo collaborator if you ever need another one, he's done a lot to make things better and easier for everyone lol

Hey, don't discredit yourself either! Absolute and I have noticed both of your contributions, alongside Zohnannor too. I actually credited you guys in a [Twitter post](https://twitter.com/_Brittank88/status/1488504079521574912). ❤️

**Comment by MainConMan** [comment]
> Hey, don't discredit yourself either! Absolute and I have noticed both of your contributions, alongside Zohnannor too.

Also NewAlexGamer, he has had a lot of good suggestions here too!

>  I actually credited you guys in a Twitter post. ❤️
TYSM! This genuinely means a lot to me! :)

> The permission system here is kinda weird and limited so unless we add you as contributors at an identical level to my own permission set, there isn't much we can do. Maybe migrating to a self-hosted issue tracker will provide a more granular permissions/roles system?

If that's the case, then I understand if Absolute decides not to add any other contributors.

**Comment by Nicko2102** [comment]
> I actually credited you guys in a [Twitter post](https://twitter.com/_Brittank88/status/1488504079521574912). ❤️

thank you, that means so much :D

> The permission system here is kinda weird and limited so unless we add you as contributors at an identical level to my own permission set, there isn't much we can do. Maybe migrating to a self-hosted issue tracker will provide a more granular permissions/roles system?

It might, but github seems to be working well for this, and I don't want to move the whole tracker just for a role, I'm happy to help the same way i have been so far

**Comment by MainConMan** [comment]
> > The permission system here is kinda weird and limited so unless we add you as contributors at an identical level to my own permission set, there isn't much we can do. Maybe migrating to a self-hosted issue tracker will provide a more granular permissions/roles system?
> 
> It might, but github seems to be working well for this, and I don't want to move the whole tracker just for a role, I'm happy to help the same way i have been so far

Moving the tracker was an idea, so it's possible that there would be more benefits to this, I'm not sure. But I do agree that it shouldn't be moved if the only thing to gain from it is a role.

**Comment by Brittank88** [comment]
> It might, but github seems to be working well for this, and I don't want to move the whole tracker just for a role, I'm happy to help the same way i have been so far

> Moving the tracker was an idea before this was mentioned, so it's possible that there would be more benefits to this, I'm not sure. But I do agree that it shouldn't be moved if the only thing to gain from it is a role.

You guys are truly wonderful. We mainly were considering migrating to a self-hosted tracker on Absolute's servers because it's then all within his own ecosystem, it's potentially much more flexible, it might allow me to contribute with the same level of permissions as Absolute (this is currently impossible for some dumb reason), etc.

So there's a bunch of good reasons, even putting aside giving you guys the credit you deserve! 😋

**Comment by MainConMan** [comment]
Would it be helpful if I added an "Update Added" column to the table I made? It shouldn't be too much effort for me to add it,  the hardest part for me will probably be getting another column in the table lol.

**Comment by Nicko2102** [comment]
> Moving the tracker was an idea before this was mentioned, so it's possible that there would be more benefits to this, I'm not sure. But I do agree that it shouldn't be moved if the only thing to gain from it is a role.

oh really i didnt know that lol

> Would it be helpful if I added an "Update Added" column to the table Brittank and I made? It shouldn't be too much effort for me to add it, the hardest part for me will probably be getting another column in the table lol.

yes that would be great, I think it will make transitioning to the BookStack thing (or whatever the mane is i forget) quite a lot easier

**Comment by zohnannor** [comment]
> I actually credited you guys in a [Twitter post](https://twitter.com/_Brittank88/status/1488504079521574912). ❤️

Wow, thank you! It means a lot! Always happy to help! :)

> The permission system here is kinda weird and limited so unless we add you as contributors at an identical level to my own permission set, there isn't much we can do.

Totally understand, We are doing well even without it I think :)

**Comment by MainConMan** [comment]
> Would it be helpful if I added an "Update Added" column to the table Brittank and I made? It shouldn't be too much effort for me to add it, the hardest part for me will probably be getting another column in the table lol.

Did this, and finished finding and adding the updates in "Enhancements" and "Other", I'll finish the rest tomorrow. :)

**Comment by MainConMan** [comment]
> > Would it be helpful if I added an "Update Added" column to the table Brittank and I made? It shouldn't be too much effort for me to add it, the hardest part for me will probably be getting another column in the table lol.
> 
> Did this, and finished finding and adding the updates in "Enhancements" and "Other", I'll finish the rest tomorrow. :)

I finished everything else!!! Also, I found another mistake I made, #297 isn't fixed yet, it needs the upcoming label. So sorry about this. I know everything else is correct though, because I went through and added all updates! :)
